version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: moodle-alt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vaIdfgRPSXzKbPPd
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - ./data/db-alt:/var/lib/mysql
    networks:
      - alt-moodle-net

  moodle:
    build: ./docker
    container_name: moodle-alt-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./wwwroot-alt:/var/www/html
      - ./data/moodledata-alt:/var/moodledata
    networks:
      - alt-moodle-net

networks:
  alt-moodle-net:
    driver: bridge
