version: '3.9'

services:
  moodle:
    image: moodlehq/moodle-php-apache:latest
    container_name: moodle
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepass
    volumes:
      - moodledata:/bitnami/moodle
    restart: always

  db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodlepass
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always

  moodle_old:
    image: moodlehq/moodle-php-apache:old-version
    container_name: moodle_old
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepass
    volumes:
      - moodleolddata:/bitnami/moodle
    restart: always

volumes:
  moodledata:
  mysqldata:
  moodleolddata:
